apiVersion: v1
kind: Pod
metadata:
  name: hello-angular
  labels:
    app: hello-angular
    name: hello-message
spec:
  containers:
  - name: hello-docker
    image: raviteja01/welcome-app:hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
