apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello-angular
    name: hello-message
  ports:
   - port: 80
     targetPort: 80
    
