apiVersion: v1    # this is injecting all env vars from a Secret
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    type: db
spec:
  containers:
  - name: mysql-image
    image: mysql:latest
    envFrom:
    - secretRef:
        name: app-secret # name of my Secret reference , injecting here
    volume:
    - name: app-secret-volume
      secret:
        secretName: app-secret     

#################  Single ENV #################################
apiVersion: v1    # this is injecting only a particular env  from a Secret
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    type: db
spec:
  containers:
  - name: mysql-image
    image: mysql:latest
    env:
    - name: MYSQL_USERNAME
      valueFrom:
        secretKeyRef: 
          name: app-config # name of the Secret which is already created
          key: MYSQL_USERNAME # must not neccesarily match with name of env

