# Secrets are used to store sensitive information like passwords
############### Imperative way #################
 # kubectl create secret generic <secret-name> --from-literal=<key>=<value>
 # kubectl create secret generic password --from-literal=MYSQL_PASSWORD=root
# 
# Another way is to import from a file

# kubectl create secret generic --from-file=<path to app_secrets.properties>


################### Declarative way ################

# 1. Encode the plain text of the secret using
#     echo -n '<password/sensitive info>' | base64
#     u will see somthing like bXlwc8=

apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
data:
  DB_HOST: bhDKLh8
  DB_UNAME: jgSO0=5
  DB_PASS: hswUP96


# to decode the secret use
# echo -n 'bhfY86' | base64 --decode

 # To view, use
 # kubectl get secrets 
 # kubectl describe secrets , to see all secret keys
 # to get it in a file
 # kubectl get secret app-secret -o yaml 